##zipkinの配置
spring:
  zipkin:
    enabled: true
    base-url: http://18.188.51.39:9411/
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1.0


##Apiのバージョンの配置
webui:
  GasCustomerContractManage: /GasCustomerContract
  GasOfferManage: /GasOffer
