# Eurekaの情報
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/

#ルート情報
zuul:
  routes:
    eleinfweb:
      path: /eleinf/**
      service-id: ELEINFWEB
    
  host:    max-total-connections: 200
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    
    
