eureka:
  client:
    serviceUrl:
      defaultZone: http://18.188.51.39:8801/eureka/
  instance:
    preferIpAddress: true

encrypt:
  failOnError: false

security:
  basic:
    enabled: false
# datasource
spring:
  zipkin:
    enabled: true
    #local用
    base-url: http://18.188.51.39:8803/
    #pcf用
    #base-url: http://zipkin-service.apps.dirpcf.net
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1.0
