server:
  port: 8093

spring:
  cloud:
    config:
      lable: master
  zipkin:
    enabled: true
    #local用
    base-url: http://172.17.210.24:8803
    #pcf用
    #base-url: http://zipkin-service.apps.dirpcf.net
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.210.24:8801/eureka/
  instance:
    preferIpAddress: true

#logging:
#  level:
#    zipkin2: DEBUG
#    zipkin.server: DEBUG
#    io.zipkin.java: DEBUG
#    org.springframework.boot: DEBUG

#---
#spring.cloud.loadbalancer.retry.enabled: true
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
#ribbon.ConnectTimeout: 250
#ribbon.ReadTimeout: 1000
#ribbon.OkToRetryOnAllOperations: true
#ribbon.MaxAutoRetriesNextServer: 2
#ribbon.MaxAutoRetries: 1

#---
#spring.devtools.restart.enabled: false
#spring.devtools.livereload.enabled: false

#fdfs:
#  soTimeout: 1501
#  connectTimeout: 601
#  thumbImage:
#    width: 150
#    height: 150
#  trackerList:
#    - 192.168.1.214:22122
#    - 192.168.1.215:22122
#spring.jmx.enabled: false

#file.path.head: http://192.168.1.214:8080/

#security:
#  ignored: /favicon.ico,/scripts/**,/styles/**,/images/**,/webjars/**
#  sessions: ALWAYS
#  oauth2:
#      sso:
#        loginPath: /login
#      client:
#        clientId: ssoclient
#        clientSecret: ssosecret
#        accessTokenUri: http://localhost/oauth/token
#        userAuthorizationUri: http://localhost/oauth/authorize
#        clientAuthenticationScheme: form
#      resource:
#        jwt:
#          keyUri: http://localhost/oauth/token_key
security:
  basic:
    enabled: false
    
securityconfig:
  logoutsuccssurl: /tosignout
  permitall: /test/**,/hystrix**
  deniedpage: /deny
  urlroles: /**/new/** = admin;
            /**/eleinf/** = admin,editor;
            /**/eleinf/** = admin
