spring:
  application:
    name: pointapi
#  profiles:
#    active: development
  cloud:
    config:
      uri: http://localhost:8802
    services:
      registrationMethod: direct

encrypt:
  failOnError: false
